# Generated by Django 2.0.6 on 2018-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('volume', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('seek', models.CharField(max_length=30)),
                ('play', models.CharField(max_length=2)),
                ('mute', models.CharField(max_length=2)),
                ('dj', models.CharField(max_length=30)),
            ],
        ),
    ]
