# Generated by Django 2.0.6 on 2018-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='play',
            field=models.BooleanField(default=True),
        ),
    ]
