# Generated by Django 2.0.6 on 2018-07-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20180725_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
